FROM nginx:1.17-alpine AS appRuntime
COPY ./Gateway/nginx/nginx.conf /etc/nginx/conf.d/default.conf.template
CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
EXPOSE $PORT