name: CI push develop

on:
  push:
    branches:
      - 'main'

jobs:

  pre-realese:
    runs-on: ubuntu-latest
    steps:
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v5.5
          with:
            append_to_pre_release_tag: "dev"
            default_bump: patch
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Create a GitHub prerelease
          uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.tag_version.outputs.new_tag }}
            release_name: Prerelease ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            prerelease: true
            
  docker:
    needs: pre-realese
    runs-on: ubuntu-latest
    steps:           
      - name: Build docker image
        env:
          REPO_TAG: ${{ secrets.DOCKER_USER }}/product-service-proba:${{ steps.tag_version.outputs.new_tag }}
          REPO: ${{ secrets.DOCKER_USER }}/product-service-proba
#          steps:
#          - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        working-directory: ./product-service
        run: docker build -t $REPO_TAG -t --no-cache .
      - name: Publish Docker image
        run: docker push $REPO_TAG      