name: CI pr develop

on:
  pull_request:
    branches:
      - 'develop'
    types: [opened, reopened, edited, synchronize] 
      

jobs:

  test:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        working-directory: ./agent
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        working-directory: ./agent
        run: mvn -B clean verify -Dspring.profiles.active=test